
name: empty-commit
on: 
  push:
  schedule:
    - cron: '* * 1 * *'
  workflow_dispatch:
jobs:
  empty-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - run: |
          npm install -g make-empty-github-commit
          $(npm bin -g)/empty-commit --repo NullableSafety/gitsync_repo --message "Empty commit for GHA" --branch empty
