
name: empty-commit
on: 
  push:
  schedule:
    - cron: '* * 1 * *'
  workflow_dispatch:
jobs:
  empty-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - run: |
          git clone https://github.com/bahmutov/make-empty-github-commit
          cd make-empty-github-commit
          npm install
          node bin/empty.js --repo NullableSafety/gitsync_repo --message "Empty commit for GHA" --branch empty
